//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SogetiStaffingPlanner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Dev_ClientOpportunitiesEntities : DbContext
    {
        public Dev_ClientOpportunitiesEntities()
            : base("name=Dev_ClientOpportunitiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<MainView_Result> MainView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MainView_Result>("MainView");
        }
    }
}
